### ISSUE TITLE
Provide an option to display more information like: pid, command name

### ISSUE THREAD

**Issue by loggerhead** [ncrocfer/whatportis#16]
I think display command and pid is useful, because sometimes we just want to kill the process which take up the port and find out which command caused that the port be taken. 

![1.png](https://ooo.0o0.ooo/2016/02/16/56c332c48a0ed.png)

So...Is there any plan to support this feature? Or is this possible?

**Comment by timofurrer** [comment]
@loggerhead whatportis implements at the moment only port-service lookup from the IANA database but not from your system.
There is/was another issue to discuss if this should be implemented or not.
What's the problem with `lsof` it's almost the same amount to type?

**Comment by ncrocfer** [comment]
Sorry, as @timofurrer said it, find the service running in your system is not the purpose of `whatportis`. I think other tools do it much better (see this other [answer](https://github.com/ncrocfer/whatportis/issues/8#issuecomment-181325251)):

    $ netstat -plnt |grep apache2
    tcp6       0      0 :::80                   :::*                    LISTEN      1783/apache2

According to me it's not useful to reinvent the wheel.

**Comment by loggerhead** [comment]
@timofurrer No problem. Because my English maybe confuse for you, so I just use the output of `lsof` to explain what I mean :)
@ncrocfer Yes, you are right.
