### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'click==6.2' distribution was not found and is required by whatportis

### ISSUE THREAD

**Issue by neo1218** [ncrocfer/whatportis#17]
![screen shot 2016-12-26 at 13 53 36](https://cloud.githubusercontent.com/assets/10671733/21476389/0c47fb3e-cb73-11e6-9e27-00eec3d00d38.png)

I use whatportis in virtualenv and I successfully install click==6.2 in virtualenv.

**Comment by timofurrer** [comment]
How did you install `whatportis` exactly?

The following works perfectly fine on my machine: (Ubuntu 16.10)

```bash
virtualenv testenv -p python2.7
source testenv/bin/activate
python -m pip install whatportis
whatportis 1080
```

**Comment by neo1218** [comment]
Thanks for your answer

I use ```pip install whatportis```
and I follow your method, the same error
![screen shot 2016-12-26 at 18 27 20](https://cloud.githubusercontent.com/assets/10671733/21480566/40563c08-cb99-11e6-8950-ec1e35b7b90d.png)

my machine is ```OSX Yosemite 10.10.4```, my pip version is ```9.0.1```

and very strange, there are several successful install, when I tried many times.
I think maybe it's my pip problem...

**Comment by timofurrer** [comment]
I think your `whatportis` is the one installed outside of your virtualenv and there `click` is not installed.

Can you try to call `whatportis` with an absolute path, like: `testenv/bin/whatportis`?
