### ISSUE TITLE
--like doesnt work correctly

### ISSUE THREAD

**Issue by Stefan-mcp** [ncrocfer/whatportis#19]
when using the like flag, no results are returned regardless of the input 

whatportis 123
+------+------+----------+-----------------------+
| Name | Port | Protocol | Description           |
+------+------+----------+-----------------------+
| ntp  | 123  | tcp, udp | Network Time Protocol |
+------+------+----------+-----------------------+

whatportis 123 --like
     No ports found for '123'

whatportis mysql --like
    No ports found for 'mysql'

**Comment by ncrocfer** [comment]
I need more info please : whatportis version, Python version, OS, etc.

Tested on my side using different config and your examples work :

```
$ whatportis mysql --like
+----------------+-------+----------+-----------------------------------+
| Name           |  Port | Protocol | Description                       |
+----------------+-------+----------+-----------------------------------+
| mysql-proxy    |  6446 | tcp, udp | MySQL Proxy                       |
| mysql-cm-agent |  1862 | tcp, udp | MySQL Cluster Manager Agent       |
| mysql          |  3306 | tcp, udp | MySQL                             |
| mysql-im       |  2273 | tcp, udp | MySQL Instance Manager            |
| mysql-cluster  |  1186 | tcp, udp | MySQL Cluster Manager             |
| mysqlx         | 33060 |   tcp    | MySQL Database Extended Interface |
+----------------+-------+----------+-----------------------------------+
```

**Comment by ncrocfer** [comment]
Closed due to inactivity.
