### ISSUE TITLE
Python requests version

### ISSUE THREAD

**Issue by yogeshojha** [ncrocfer/whatportis#21]
Hi, I am trying to figure out if there is a specific reason why `whatportis` uses `requests==2.23.0` and not `requests>=2.23.0`?
https://github.com/ncrocfer/whatportis/blob/e8e166513285a31f79334ad511c355553e288939/setup.py#L23

I've been using whatportis in one of our projects called reNgine, whatportis is an amazing tool out there, but this is causing conflict due to mismatched requests version. 

Can't we use `requests>=2.23.0`?

Thanks 🚀

**Comment by ncrocfer** [comment]
Hi @yogeshojha ,

For me it's not a good practice to not pin your dependencies. When you use CI/CD you want to be sure your deployment will work, event if you redeploy your app after several months, and it's so easy to have conflict between sub-dependencies when our dependencies are not pinned 😄 

From [pip-tools](https://github.com/jazzband/pip-tools):

> A set of command line tools to help you keep your pip-based packages fresh, even when you've pinned them. You do pin them, right? (In building your Python application and its dependencies for production, you want to make sure that your builds are predictable and deterministic.)

But I can try to upgrade all the packages and use the last version of requests if you want (v2.25.1 as I write this comment). But sorry I will still pin it ^^

**Comment by yogeshojha** [comment]
Thank you @ncrocfer for your response.

My bad, I did not mean to unpin the version, I understand your concern, but I was asking if we could use requests anything later than 2.23.X :D 

Can we please upgrade this to 2.25.1? 

Thank you very much

**Comment by ncrocfer** [comment]
Yes of course, I will try to check it this week ;)

**Comment by ncrocfer** [comment]
Done in **v0.8.2** (https://pypi.org/project/whatportis/0.8.2/).

**Comment by yogeshojha** [comment]
Perfect. Thank you so much <3
