### ISSUE TITLE
Lync/Skype ports missing

### ISSUE THREAD

**Issue by erwinbierens** [ncrocfer/whatportis#3]
Great tool! 

can you please update the db with Skype for Business/Lync and Skype consumer ports. 

Thx!

**Comment by ncrocfer** [comment]
The tool uses the [Internet Assigned Numbers Authority (IANA)](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) website to fetch its database and automatically update the **ports.db** file.

This organization is responsible for maintaining the official assignments of port numbers, unfortunately it seems that Skype for Business/Lync and Skype consumer ports are not considered as official ports (http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=Skype). Sorry :)
