### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by CBrowne** [ncrocfer/whatportis#5]
Hey, cool tool! Is there anyway to contribute to this to fill the blanks about some port numbers that lana isn't storing information for?

**Comment by ncrocfer** [comment]
Indeed it's a feature requested by other users (see here #6), it will be included in a future version :)

**Comment by ncrocfer** [comment]
The **ports.db** file is now a **JSON** one (see #11). But I want to add a new field before opening contributions, named "Official" for example, to display if a port is extracted from the IANA website or if it is added by a user.

By the way a new option (`--official`) could be created.

A validation for each PR adding a new port will be asked to prevent abuse (2 or 3 users should say :+1: to accept a new one).

**Comment by CBrowne** [comment]
Sounds good (y)

**Comment by thorsummoner** [comment]
from the core api I would recommend exposing multiple constants, something like:

```
import whatportis
whatportis.IANA
whatportis.COMMUNITY
```

I also sort of expected this to expose a dictionary, not like a complicated database thing. My fork will probably be very different if anyone wants that.

**Comment by timofurrer** [comment]
> I also sort of expected this to expose a dictionary, not like a complicated database thing. My fork will probably be very different if anyone wants that.

The current implementation does not use a *complicated database thing*. It actually uses a JSON file which could be exposed as a dictionary.

> from the core api I would recommend exposing multiple constants, something like:
> ```python
>import whatportis
>whatportis.IANA
>whatportis.COMMUNITY
>```

As @ncrocfer suggested: there has to be a new field in the JSON db to specify whether a port is official by IANA or a community specified port. 

I can have a look at it.

**Comment by ncrocfer** [comment]
Closed due to inactivity.
