### ISSUE TITLE
Show what application is listening on a local port

### ISSUE THREAD

**Issue by nzjrs** [ncrocfer/whatportis#8]
From the description "what service is listening on a given port" I would have expected whatport is to print the application which is running on that port on the current machine.

However it prints what the standardized or expected application on that port *should be*. For example, if I make a python application on my local machine which happens to listen on port 6379, whatportis will show 'redis'.

Can you make whatportis actually check the local machine port usage, `fuser user -n tcp PORT` or `netstat -alnp | grep PORT`, etc?

Or maybe the README could be amended to be clearer on this point.

**Comment by ncrocfer** [comment]
Yep, I undestand the confusion. The first option (whatportis showing the actual port) is not the purpose of the tool, others do it much better (netstat, nmap...).

However you can update the README to be clearer and send me a PR if you want.
Ex : `what service is listening on a given port `
==> `what service is normally listening on a given port `

**Comment by ncrocfer** [comment]
Added in https://github.com/ncrocfer/whatportis/commit/50bfeab3acb154507d0942eb1204010fee8e1a7c :)
